import { cp, mkdir, rm, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const dist = join(root, "dist");
const apiOrigin = (process.env.MOBILE_API_ORIGIN || "https://ambassadorcompanion.netlify.app").replace(/\/$/, "");

if (!apiOrigin.startsWith("https://")) {
  throw new Error("MOBILE_API_ORIGIN must use HTTPS");
}

const shellEntries = [
  "index.html",
  "privacy.html",
  "manifest.webmanifest",
  "favicon.svg",
  "apple-touch-icon.png",
  "icon-192.png",
  "icon-512.png",
  "setlists-default.json",
  "sw.js",
  "assets",
  "data",
  "js"
];

await rm(dist, { recursive: true, force: true });
await mkdir(dist, { recursive: true });

for (const entry of shellEntries) {
  await cp(join(root, entry), join(dist, entry), { recursive: true });
}

await writeFile(
  join(dist, "mobile-runtime.js"),
  `/* Generated by scripts/prepare-mobile.mjs. */\nwindow.K2C_API_ORIGIN = ${JSON.stringify(apiOrigin)};\nwindow.K2C_API_PATH = "/.netlify/functions/mobile-data";\n`
);

console.log(`Prepared Ambassador Companion mobile shell for ${apiOrigin}`);
